import { test, expect } from "@playwright/test"

test("mockup history updates controls and restores pointer edits", async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 })
  await page.goto("./#tools/mockup")
  const items = page.locator("[data-item]")
  await expect(items.first()).toBeVisible()
  const initial = await items.count()
  const undo = page.getByRole("button", { name: "Undo (Ctrl+Z)", exact: true })
  const redo = page.getByRole("button", { name: "Redo (Ctrl+Shift+Z)", exact: true })
  const addPanel = page.locator("section").filter({ has: page.getByRole("heading", { name: "Add to scene", exact: true }) })
  await expect(undo).toBeDisabled()
  await expect(redo).toBeDisabled()
  await addPanel.getByRole("button", { name: "Phone", exact: true }).click()
  await expect(items).toHaveCount(initial + 1)
  await expect(undo).toBeEnabled()
  await undo.click()
  await expect(items).toHaveCount(initial)
  await expect(redo).toBeEnabled()
  await redo.click()
  await expect(items).toHaveCount(initial + 1)
  const item = items.last()
  const previous = await item.evaluate((element) => (element as HTMLElement).style.left)
  const bounds = await item.boundingBox()
  if (!bounds) throw new Error("Missing mockup bounds")
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2)
  await page.mouse.down()
  await page.mouse.move(bounds.x + bounds.width / 2 + 50, bounds.y + bounds.height / 2, { steps: 6 })
  await page.mouse.up()
  await expect.poll(() => item.evaluate((element) => (element as HTMLElement).style.left)).not.toBe(previous)
  await undo.click()
  await expect.poll(() => item.evaluate((element) => (element as HTMLElement).style.left)).toBe(previous)
  await expect(redo).toBeEnabled()
  await addPanel.getByRole("button", { name: "Shape", exact: true }).click()
  await expect(redo).toBeDisabled()
  const newItem = items.last()
  await page.locator('button[title="Lock"]').first().click()
  await expect(page.locator('button[title="Unlock"]').first()).toBeVisible()
  await page.locator('button[title="Hide"]').first().click()
  await expect(newItem).toBeHidden()
  await page.locator('button[title="Show"]').first().click()
  await expect(newItem).toBeVisible()
  const download = page.waitForEvent("download")
  await page.getByRole("button", { name: /^PNG \d/ }).click()
  expect((await download).suggestedFilename()).toMatch(/\.png$/)
})

test("all ten 3D presets render and export PNG snapshots", async ({ page }) => {
  test.setTimeout(120000)
  const errors: string[] = []
  page.on("pageerror", (error) => errors.push(error.message))
  await page.goto("./#tools/three")
  for (const preset of ["Liquid sphere", "Wave grid", "Galaxy", "Pearl", "Live gradient", "Glass", "Globe", "Landscape", "Floating shapes", "Tunnel"]) {
    await page.getByRole("button", { name: preset, exact: true }).click()
    const canvas = page.locator("main canvas")
    await expect(canvas).toBeVisible()
    await expect.poll(() => canvas.evaluate((element) => (element as HTMLCanvasElement).width)).toBeGreaterThan(0)
    const download = page.waitForEvent("download")
    await page.getByRole("button", { name: "PNG snapshot", exact: true }).click()
    expect((await download).suggestedFilename()).toMatch(/^3d-.*\.png$/)
  }
  expect(errors).toEqual([])
})
